apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "replik8s.name" . }}
  labels:
    {{- include "replik8s.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "replik8s.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "replik8s.name" . }}
  apiGroup: rbac.authorization.k8s.io
