{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "replik8s.serviceAccountName" . }}
  labels:
{{ include "replik8s.labels" . | nindent 4 }}
{{- end -}}
